services:
  nginx:
    image: nginx:1.27.4
    container_name: nginx
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/ssl:/etc/nginx/ssl:ro
    - ./cam-www:/usr/share/nginx/html:ro
    ports:
    - "80:80"
    - "443:443"
    restart: always
    networks:
      - ssnet-cam

networks:
  ssnet-cam:
