services:
  nginx:
    image: nginx:1.27.4
    container_name: nginx
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/ssl:/etc/nginx/ssl:ro
    - ./cam-www/public:/usr/share/nginx/html:ro
    ports:
    - "80:80"
    - "443:443"
    restart: always
    networks:
      - cam-net
  camera-capture:
    build: ./cam-www
    container_name: camera-capture
    restart: always
    networks:
      - cam-net
  mqtt:
    image: eclipse-mosquitto:2.0.21
    container_name: mosquitto
    restart: always
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/certs:/mosquitto/certs
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      # - "1883:1883"
      - "8883:8883"
    networks:
      - cam-net

networks:
  cam-net:
